name: 🚀 Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: git config --global user.email "version@release.com"
      - run: git config --global user.name "Version Release"
      - name: If variable exists do
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          DEPLOY_PATCH: ${{ contains(github.event.head_commit.message, '[PATCH]') }}
          DEPLOY_MINOR: ${{ contains(github.event.head_commit.message, '[MINOR]') }}
          DEPLOY_MAJOR: ${{ contains(github.event.head_commit.message, '[MAJOR]') }}
        run: |
          if ${DEPLOY_PATCH} == true; then
            npm install
            git commit -am "Autocommit version patch"
            npm version patch
            npm run deploy
            git commit -am "New version upgrade"
            git push
          elif ${DEPLOY_MINOR} == true; then
            npm install
            git commit -am "Autocommit version patch"
            npm version patch
            npm run minor
            git commit -am "New version upgrade"
            git push
          elif ${DEPLOY_MAJOR} == true; then
            npm install
            git commit -am "Autocommit version patch"
            npm version major
            npm run deploy
            git commit -am "New version upgrade"
            git push
          fi
      - run: git push
