name: 🚀 Publish to NPM

on:
  push:
    branches:
      - main

inputs:
  deploy:
    description: "The version to be deployed: major, minor or patch"
    required: false
    default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: git config --global user.email "version@release.com"
      - run: git config --global user.name "Version Release"
      - name: If variable exists do
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          deploy: ${{ inputs.deploy }}
        run: |
          if [ "$deploy" != "" ]
          then
            npm install
            git commit -am "Autocommit version patch"
            npm version $deploy
            npm run deploy
            git commit -am "New version upgrade"
            git push
          fi
